# Generated by Django 2.2.4 on 2019-09-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHoard', '0002_auto_20190911_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='translator',
            field=models.ManyToManyField(blank=True, null=True, related_name='texts', to='WordHoard.Translator'),
        ),
    ]
