# Generated by Django 2.0.13 on 2019-09-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHoard', '0003_auto_20190911_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='translator',
            field=models.ManyToManyField(blank=True, related_name='texts', to='WordHoard.Translator'),
        ),
    ]
