# Generated by Django 2.0.13 on 2019-10-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHoard', '0005_text_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='time_period',
            field=models.CharField(choices=[('The Classical Period (1200 BCE-455 CE)', 'The Classical Period (1200 BCE-455 CE)'), ('The Medieval Period (455-1485 CE)', 'The Medieval Period (455-1485 CE)'), ('The Renaissance and Reformation (1485-1660)', 'The Renaissance and Reformation (1485-1660)'), ('The Englightenment (1660-1790)', 'The Englightenment (1660-1790)'), ('The Romantic Period (1790-1830)', 'The Romantic Period (1790-1830)'), ('The Victorian Period (1832-1901', 'The Victorian Period (1832-1901'), ('The Modern Period (1914-1945)', 'The Modern Period (1914-1945)'), ('The PostModern Period (1945-Present Day)', 'The PostModern Period (1945-Present Day)'), ('Unknown', 'Unknown')], default='UNK', max_length=50),
        ),
    ]
